export const categories = [
    { id: 'cardiac', label: 'Cardiovascular System' },
    { id: 'respiratory', label: 'Respiratory System' },
    { id: 'neuro', label: 'Neurological System' },
    { id: 'gi', label: 'Gastrointestinal System' },
    { id: 'renal', label: 'Renal/Urinary System' },
    { id: 'endocrine', label: 'Endocrine System' },
    { id: 'musculoskeletal', label: 'Musculoskeletal System' },
    { id: 'integumentary', label: 'Integumentary System' },
    { id: 'immune', label: 'Immune System' },
    { id: 'hematologic', label: 'Hematologic System' },
    { id: 'reproductive', label: 'Reproductive System / OB-GYN' },
    { id: 'peds', label: 'Pediatrics' },
    { id: 'geriatrics', label: 'Geriatrics' },
    { id: 'mental-health', label: 'Mental Health / Psychosocial Integrity' },
    { id: 'pharmacology', label: 'Medications / Pharmacology' },
    { id: 'safety', label: 'Safety and Infection Control' },
    { id: 'ethics', label: 'Ethical and Legal Issues' },
    { id: 'prioritization', label: 'Prioritization and Delegation' },
    { id: 'health-promotion', label: 'Health Promotion and Maintenance' },
    { id: 'emergency', label: 'Emergency and Critical Care' },
];